import { SkillNode } from '@/pages/Builder';

export interface SkillCategory {
  id: string;
  name: string;
  icon: string;
  skills: SkillNode[];
}

export const SKILLS_LIBRARY: SkillCategory[] = [
  {
    id: 'programming',
    name: 'Программирование',
    icon: 'Code',
    skills: [
      {
        id: 'skill-python',
        name: 'Python',
        status: 'not-started',
        progress: 0,
        description: 'Универсальный язык программирования',
      },
      {
        id: 'skill-javascript',
        name: 'JavaScript',
        status: 'not-started',
        progress: 0,
        description: 'Язык для веб-разработки',
      },
      {
        id: 'skill-typescript',
        name: 'TypeScript',
        status: 'not-started',
        progress: 0,
        description: 'JavaScript с типами',
      },
      {
        id: 'skill-react',
        name: 'React',
        status: 'not-started',
        progress: 0,
        description: 'Библиотека для UI',
      },
      {
        id: 'skill-nodejs',
        name: 'Node.js',
        status: 'not-started',
        progress: 0,
        description: 'JavaScript на сервере',
      },
      {
        id: 'skill-git',
        name: 'Git',
        status: 'not-started',
        progress: 0,
        description: 'Система контроля версий',
      },
    ],
  },
  {
    id: 'design',
    name: 'Дизайн',
    icon: 'Palette',
    skills: [
      {
        id: 'skill-figma',
        name: 'Figma',
        status: 'not-started',
        progress: 0,
        description: 'Инструмент для UI/UX дизайна',
      },
      {
        id: 'skill-photoshop',
        name: 'Photoshop',
        status: 'not-started',
        progress: 0,
        description: 'Редактор растровой графики',
      },
      {
        id: 'skill-typography',
        name: 'Типографика',
        status: 'not-started',
        progress: 0,
        description: 'Работа со шрифтами',
      },
      {
        id: 'skill-color-theory',
        name: 'Теория цвета',
        status: 'not-started',
        progress: 0,
        description: 'Подбор цветовых палитр',
      },
      {
        id: 'skill-ux-research',
        name: 'UX исследования',
        status: 'not-started',
        progress: 0,
        description: 'Изучение потребностей пользователей',
      },
      {
        id: 'skill-prototyping',
        name: 'Прототипирование',
        status: 'not-started',
        progress: 0,
        description: 'Создание интерактивных прототипов',
      },
    ],
  },
  {
    id: 'data',
    name: 'Данные',
    icon: 'Database',
    skills: [
      {
        id: 'skill-sql',
        name: 'SQL',
        status: 'not-started',
        progress: 0,
        description: 'Работа с базами данных',
      },
      {
        id: 'skill-pandas',
        name: 'Pandas',
        status: 'not-started',
        progress: 0,
        description: 'Анализ данных в Python',
      },
      {
        id: 'skill-numpy',
        name: 'NumPy',
        status: 'not-started',
        progress: 0,
        description: 'Вычисления с массивами',
      },
      {
        id: 'skill-excel',
        name: 'Excel',
        status: 'not-started',
        progress: 0,
        description: 'Электронные таблицы',
      },
      {
        id: 'skill-powerbi',
        name: 'Power BI',
        status: 'not-started',
        progress: 0,
        description: 'Визуализация данных',
      },
      {
        id: 'skill-tableau',
        name: 'Tableau',
        status: 'not-started',
        progress: 0,
        description: 'Аналитические дашборды',
      },
    ],
  },
  {
    id: 'devops',
    name: 'DevOps',
    icon: 'Settings',
    skills: [
      {
        id: 'skill-docker',
        name: 'Docker',
        status: 'not-started',
        progress: 0,
        description: 'Контейнеризация приложений',
      },
      {
        id: 'skill-kubernetes',
        name: 'Kubernetes',
        status: 'not-started',
        progress: 0,
        description: 'Оркестрация контейнеров',
      },
      {
        id: 'skill-linux',
        name: 'Linux',
        status: 'not-started',
        progress: 0,
        description: 'Администрирование серверов',
      },
      {
        id: 'skill-cicd',
        name: 'CI/CD',
        status: 'not-started',
        progress: 0,
        description: 'Автоматизация доставки',
      },
      {
        id: 'skill-aws',
        name: 'AWS',
        status: 'not-started',
        progress: 0,
        description: 'Облачная платформа Amazon',
      },
      {
        id: 'skill-terraform',
        name: 'Terraform',
        status: 'not-started',
        progress: 0,
        description: 'Infrastructure as Code',
      },
    ],
  },
  {
    id: 'soft-skills',
    name: 'Soft Skills',
    icon: 'Users',
    skills: [
      {
        id: 'skill-communication',
        name: 'Коммуникация',
        status: 'not-started',
        progress: 0,
        description: 'Эффективное общение',
      },
      {
        id: 'skill-teamwork',
        name: 'Командная работа',
        status: 'not-started',
        progress: 0,
        description: 'Сотрудничество в команде',
      },
      {
        id: 'skill-time-management',
        name: 'Тайм-менеджмент',
        status: 'not-started',
        progress: 0,
        description: 'Управление временем',
      },
      {
        id: 'skill-problem-solving',
        name: 'Решение проблем',
        status: 'not-started',
        progress: 0,
        description: 'Критическое мышление',
      },
      {
        id: 'skill-presentation',
        name: 'Презентации',
        status: 'not-started',
        progress: 0,
        description: 'Публичные выступления',
      },
      {
        id: 'skill-leadership',
        name: 'Лидерство',
        status: 'not-started',
        progress: 0,
        description: 'Управление командой',
      },
    ],
  },
  {
    id: 'business',
    name: 'Бизнес',
    icon: 'Briefcase',
    skills: [
      {
        id: 'skill-marketing',
        name: 'Маркетинг',
        status: 'not-started',
        progress: 0,
        description: 'Продвижение продуктов',
      },
      {
        id: 'skill-sales',
        name: 'Продажи',
        status: 'not-started',
        progress: 0,
        description: 'Техники продаж',
      },
      {
        id: 'skill-finance',
        name: 'Финансы',
        status: 'not-started',
        progress: 0,
        description: 'Финансовая грамотность',
      },
      {
        id: 'skill-project-management',
        name: 'Управление проектами',
        status: 'not-started',
        progress: 0,
        description: 'Agile, Scrum, Kanban',
      },
      {
        id: 'skill-business-analysis',
        name: 'Бизнес-анализ',
        status: 'not-started',
        progress: 0,
        description: 'Анализ требований',
      },
      {
        id: 'skill-negotiation',
        name: 'Переговоры',
        status: 'not-started',
        progress: 0,
        description: 'Ведение переговоров',
      },
    ],
  },
];

export const SKILL_BRANCHES = [
  {
    id: 'frontend-basics',
    name: 'Основы Frontend',
    description: 'HTML, CSS, JavaScript',
    skills: [
      {
        id: 'skill-html',
        name: 'HTML',
        status: 'not-started' as const,
        progress: 0,
        description: 'Разметка веб-страниц',
      },
      {
        id: 'skill-css',
        name: 'CSS',
        status: 'not-started' as const,
        progress: 0,
        description: 'Стилизация элементов',
        dependencies: ['skill-html'],
      },
      {
        id: 'skill-js-basics',
        name: 'JavaScript основы',
        status: 'not-started' as const,
        progress: 0,
        description: 'Основы программирования на JS',
        dependencies: ['skill-html', 'skill-css'],
      },
    ],
  },
  {
    id: 'backend-basics',
    name: 'Основы Backend',
    description: 'Сервер, БД, API',
    skills: [
      {
        id: 'skill-server',
        name: 'Серверная разработка',
        status: 'not-started' as const,
        progress: 0,
        description: 'HTTP, REST API',
      },
      {
        id: 'skill-database',
        name: 'Базы данных',
        status: 'not-started' as const,
        progress: 0,
        description: 'SQL, PostgreSQL',
        dependencies: ['skill-server'],
      },
      {
        id: 'skill-auth',
        name: 'Аутентификация',
        status: 'not-started' as const,
        progress: 0,
        description: 'JWT, OAuth',
        dependencies: ['skill-database'],
      },
    ],
  },
  {
    id: 'data-science-path',
    name: 'Путь Data Science',
    description: 'Python → Pandas → ML',
    skills: [
      {
        id: 'skill-python-ds',
        name: 'Python для DS',
        status: 'not-started' as const,
        progress: 0,
        description: 'Основы Python',
      },
      {
        id: 'skill-data-analysis',
        name: 'Анализ данных',
        status: 'not-started' as const,
        progress: 0,
        description: 'Pandas, NumPy',
        dependencies: ['skill-python-ds'],
      },
      {
        id: 'skill-ml',
        name: 'Machine Learning',
        status: 'not-started' as const,
        progress: 0,
        description: 'Scikit-learn',
        dependencies: ['skill-data-analysis'],
      },
    ],
  },
  {
    id: 'ui-ux-path',
    name: 'UI/UX Дизайн',
    description: 'От основ до прототипов',
    skills: [
      {
        id: 'skill-design-basics',
        name: 'Основы дизайна',
        status: 'not-started' as const,
        progress: 0,
        description: 'Композиция, цвет, типографика',
      },
      {
        id: 'skill-figma-adv',
        name: 'Figma Advanced',
        status: 'not-started' as const,
        progress: 0,
        description: 'Компоненты, Auto Layout',
        dependencies: ['skill-design-basics'],
      },
      {
        id: 'skill-ux-design',
        name: 'UX Design',
        status: 'not-started' as const,
        progress: 0,
        description: 'Исследования, прототипы',
        dependencies: ['skill-figma-adv'],
      },
    ],
  },
];
