import { SkillTree } from '@/pages/Builder';

export const TREE_TEMPLATES: SkillTree[] = [
  {
    id: 'python-dev',
    name: 'Python Developer',
    description: 'Путь от основ Python до профессионального разработчика',
    progress: 45,
    nodes: [
      {
        id: 'basics',
        name: 'Основы Python',
        status: 'completed',
        progress: 100,
        category: 'foundation',
        children: [
          {
            id: 'syntax',
            name: 'Синтаксис',
            status: 'completed',
            progress: 100,
            description: 'Базовый синтаксис Python: переменные, операторы, условия',
          },
          {
            id: 'data-types',
            name: 'Типы данных',
            status: 'completed',
            progress: 100,
            description: 'Работа со строками, числами, списками, словарями',
            dependencies: ['syntax'],
          },
          {
            id: 'functions',
            name: 'Функции',
            status: 'completed',
            progress: 100,
            description: 'Создание и использование функций, аргументы, возврат значений',
            dependencies: ['data-types'],
          },
        ],
      },
      {
        id: 'web-dev',
        name: 'Веб-разработка',
        status: 'in-progress',
        progress: 60,
        category: 'backend',
        dependencies: ['basics'],
        children: [
          {
            id: 'flask',
            name: 'Flask',
            status: 'completed',
            progress: 100,
            description: 'Микрофреймворк для создания веб-приложений',
            resources: ['https://flask.palletsprojects.com/'],
            dependencies: ['functions'],
          },
          {
            id: 'django',
            name: 'Django',
            status: 'in-progress',
            progress: 60,
            description: 'Полнофункциональный фреймворк для веб-разработки',
            resources: ['https://docs.djangoproject.com/'],
            notes: 'Прохожу курс на Stepik, закончу к 15 декабря',
            dependencies: ['flask'],
          },
          {
            id: 'fastapi',
            name: 'FastAPI',
            status: 'not-started',
            progress: 0,
            description: 'Современный фреймворк для создания API',
            dependencies: ['django'],
          },
        ],
      },
      {
        id: 'data-science',
        name: 'Data Science',
        status: 'not-started',
        progress: 0,
        category: 'data',
        dependencies: ['basics'],
        children: [
          {
            id: 'pandas',
            name: 'Pandas',
            status: 'not-started',
            progress: 0,
            description: 'Библиотека для анализа данных',
            dependencies: ['functions'],
          },
          {
            id: 'numpy',
            name: 'NumPy',
            status: 'not-started',
            progress: 0,
            description: 'Библиотека для работы с массивами',
            dependencies: ['pandas'],
          },
          {
            id: 'matplotlib',
            name: 'Matplotlib',
            status: 'not-started',
            progress: 0,
            description: 'Визуализация данных',
            dependencies: ['numpy'],
          },
        ],
      },
    ],
  },
  {
    id: 'web-frontend',
    name: 'Frontend Developer',
    description: 'Полный путь в современную фронтенд-разработку',
    progress: 30,
    nodes: [
      {
        id: 'html-css',
        name: 'HTML & CSS',
        status: 'completed',
        progress: 100,
        category: 'foundation',
        children: [
          {
            id: 'html-basics',
            name: 'HTML основы',
            status: 'completed',
            progress: 100,
          },
          {
            id: 'css-basics',
            name: 'CSS основы',
            status: 'completed',
            progress: 100,
            dependencies: ['html-basics'],
          },
          {
            id: 'responsive',
            name: 'Адаптивная вёрстка',
            status: 'completed',
            progress: 100,
            dependencies: ['css-basics'],
          },
        ],
      },
      {
        id: 'javascript',
        name: 'JavaScript',
        status: 'in-progress',
        progress: 50,
        category: 'programming',
        dependencies: ['html-css'],
        children: [
          {
            id: 'js-basics',
            name: 'JS основы',
            status: 'completed',
            progress: 100,
          },
          {
            id: 'dom',
            name: 'DOM манипуляции',
            status: 'in-progress',
            progress: 50,
            dependencies: ['js-basics'],
          },
          {
            id: 'async',
            name: 'Асинхронность',
            status: 'not-started',
            progress: 0,
            dependencies: ['dom'],
          },
        ],
      },
      {
        id: 'react',
        name: 'React',
        status: 'not-started',
        progress: 0,
        category: 'framework',
        dependencies: ['javascript'],
        children: [
          {
            id: 'react-basics',
            name: 'React основы',
            status: 'not-started',
            progress: 0,
            dependencies: ['async'],
          },
          {
            id: 'hooks',
            name: 'Хуки',
            status: 'not-started',
            progress: 0,
            dependencies: ['react-basics'],
          },
          {
            id: 'routing',
            name: 'Роутинг',
            status: 'not-started',
            progress: 0,
            dependencies: ['hooks'],
          },
        ],
      },
    ],
  },
  {
    id: 'ui-ux',
    name: 'UI/UX Designer',
    description: 'От основ дизайна до создания пользовательских интерфейсов',
    progress: 20,
    nodes: [
      {
        id: 'design-basics',
        name: 'Основы дизайна',
        status: 'in-progress',
        progress: 40,
        category: 'foundation',
        children: [
          {
            id: 'typography',
            name: 'Типографика',
            status: 'completed',
            progress: 100,
          },
          {
            id: 'color-theory',
            name: 'Теория цвета',
            status: 'in-progress',
            progress: 50,
            dependencies: ['typography'],
          },
          {
            id: 'composition',
            name: 'Композиция',
            status: 'not-started',
            progress: 0,
            dependencies: ['color-theory'],
          },
        ],
      },
      {
        id: 'tools',
        name: 'Инструменты',
        status: 'not-started',
        progress: 0,
        category: 'tools',
        dependencies: ['design-basics'],
        children: [
          {
            id: 'figma',
            name: 'Figma',
            status: 'not-started',
            progress: 0,
          },
          {
            id: 'photoshop',
            name: 'Photoshop',
            status: 'not-started',
            progress: 0,
          },
        ],
      },
      {
        id: 'ux',
        name: 'UX исследования',
        status: 'not-started',
        progress: 0,
        category: 'research',
        dependencies: ['design-basics'],
        children: [
          {
            id: 'user-research',
            name: 'Исследование пользователей',
            status: 'not-started',
            progress: 0,
          },
          {
            id: 'wireframes',
            name: 'Вайрфреймы',
            status: 'not-started',
            progress: 0,
            dependencies: ['user-research'],
          },
          {
            id: 'prototyping',
            name: 'Прототипирование',
            status: 'not-started',
            progress: 0,
            dependencies: ['wireframes'],
          },
        ],
      },
    ],
  },
  {
    id: 'devops',
    name: 'DevOps Engineer',
    description: 'Автоматизация и управление инфраструктурой',
    progress: 15,
    nodes: [
      {
        id: 'linux',
        name: 'Linux',
        status: 'in-progress',
        progress: 60,
        category: 'foundation',
        children: [
          {
            id: 'bash',
            name: 'Bash scripting',
            status: 'in-progress',
            progress: 60,
          },
          {
            id: 'permissions',
            name: 'Права доступа',
            status: 'not-started',
            progress: 0,
            dependencies: ['bash'],
          },
        ],
      },
      {
        id: 'containers',
        name: 'Контейнеризация',
        status: 'not-started',
        progress: 0,
        category: 'containers',
        dependencies: ['linux'],
        children: [
          {
            id: 'docker',
            name: 'Docker',
            status: 'not-started',
            progress: 0,
          },
          {
            id: 'kubernetes',
            name: 'Kubernetes',
            status: 'not-started',
            progress: 0,
            dependencies: ['docker'],
          },
        ],
      },
      {
        id: 'ci-cd',
        name: 'CI/CD',
        status: 'not-started',
        progress: 0,
        category: 'automation',
        dependencies: ['containers'],
        children: [
          {
            id: 'github-actions',
            name: 'GitHub Actions',
            status: 'not-started',
            progress: 0,
          },
          {
            id: 'jenkins',
            name: 'Jenkins',
            status: 'not-started',
            progress: 0,
          },
        ],
      },
    ],
  },
  {
    id: 'mobile-dev',
    name: 'Mobile Developer',
    description: 'Разработка мобильных приложений',
    progress: 25,
    nodes: [
      {
        id: 'mobile-basics',
        name: 'Основы мобильной разработки',
        status: 'in-progress',
        progress: 70,
        category: 'foundation',
        children: [
          {
            id: 'ui-principles',
            name: 'Принципы UI',
            status: 'completed',
            progress: 100,
          },
          {
            id: 'navigation',
            name: 'Навигация',
            status: 'in-progress',
            progress: 50,
            dependencies: ['ui-principles'],
          },
        ],
      },
      {
        id: 'react-native',
        name: 'React Native',
        status: 'not-started',
        progress: 0,
        category: 'framework',
        dependencies: ['mobile-basics'],
        children: [
          {
            id: 'rn-basics',
            name: 'RN основы',
            status: 'not-started',
            progress: 0,
          },
          {
            id: 'native-modules',
            name: 'Нативные модули',
            status: 'not-started',
            progress: 0,
            dependencies: ['rn-basics'],
          },
        ],
      },
    ],
  },
  {
    id: 'data-analyst',
    name: 'Data Analyst',
    description: 'Анализ данных и визуализация',
    progress: 35,
    nodes: [
      {
        id: 'excel',
        name: 'Excel',
        status: 'completed',
        progress: 100,
        category: 'tools',
        children: [
          {
            id: 'formulas',
            name: 'Формулы',
            status: 'completed',
            progress: 100,
          },
          {
            id: 'pivot',
            name: 'Сводные таблицы',
            status: 'completed',
            progress: 100,
            dependencies: ['formulas'],
          },
        ],
      },
      {
        id: 'sql',
        name: 'SQL',
        status: 'in-progress',
        progress: 60,
        category: 'database',
        dependencies: ['excel'],
        children: [
          {
            id: 'basic-queries',
            name: 'Базовые запросы',
            status: 'completed',
            progress: 100,
          },
          {
            id: 'joins',
            name: 'JOIN операции',
            status: 'in-progress',
            progress: 50,
            dependencies: ['basic-queries'],
          },
          {
            id: 'optimization',
            name: 'Оптимизация запросов',
            status: 'not-started',
            progress: 0,
            dependencies: ['joins'],
          },
        ],
      },
      {
        id: 'visualization',
        name: 'Визуализация',
        status: 'not-started',
        progress: 0,
        category: 'analysis',
        dependencies: ['sql'],
        children: [
          {
            id: 'power-bi',
            name: 'Power BI',
            status: 'not-started',
            progress: 0,
          },
          {
            id: 'tableau',
            name: 'Tableau',
            status: 'not-started',
            progress: 0,
          },
        ],
      },
    ],
  },
];
